name: Deploy Demo

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy-demo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Test Python Tools
      run: |
        python3 src/aurora_tracker.py > /dev/null
        python3 src/aurora_art.py > /dev/null
        python3 src/aurora_graph.py > /dev/null
        python3 src/aurora_info.py > /dev/null
        echo "✅ All Python tools working correctly"
    
    - name: Test Web Dashboard
      run: |
        cd web
        python3 -m http.server 8000 &
        sleep 2
        curl -f http://localhost:8000 > /dev/null
        echo "✅ Web dashboard serving correctly"
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web